package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase data class representing accelerometer sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the accelerometer entry. Auto-generated when inserting into Supabase.
 * @property deviceType Type of device (e.g., "phone", "watch").
 * @property timestamp Unix timestamp in milliseconds when the accelerometer data was recorded.
 * @property x Acceleration along the x-axis in m/s².
 * @property y Acceleration along the y-axis in m/s².
 * @property z Acceleration along the z-axis in m/s².
 * @property received Timestamp when the data was received by the watch (Unix timestamp in milliseconds).
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class AccelerometerSensorData(
    val uuid: String? = null,
    @SerialName("device_type")
    val deviceType: Int,
    val timestamp: Long,
    val x: Float,
    val y: Float,
    val z: Float,
    val received: Long,
    val created_at: String? = null
)

