package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing heart rate sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the heart rate entry. Auto-generated when inserting into Supabase.
 * @property timestamp Timestamp in "YYYY-MM-DD HH:mm:ss" format when the heart rate data was recorded.
 * @property hr Heart rate value in beats per minute.
 * @property hrStatus Status of the heart rate measurement.
 * @property ibi List of inter-beat intervals in milliseconds.
 * @property ibiStatus List of status values corresponding to each inter-beat interval.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class HeartRateSensorData(
    val uuid: String? = null,
    val timestamp: String,
    val hr: Int,
    val hrStatus: Int,
    val ibi: List<Int>,
    val ibiStatus: List<Int>,
    val created_at: String? = null
)

