package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase data class representing heart rate sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the heart rate entry. Auto-generated when inserting into Supabase.
 * @property deviceType Type of device (e.g., "phone", "watch").
 * @property timestamp Unix timestamp in milliseconds when the heart rate data was recorded.
 * @property hr Heart rate value in beats per minute.
 * @property hrStatus Status of the heart rate measurement.
 * @property ibi List of inter-beat intervals in milliseconds.
 * @property ibiStatus List of status values corresponding to each inter-beat interval.
 * @property received Timestamp when the data was received by the watch (Unix timestamp in milliseconds).
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class HeartRateSensorData(
    val uuid: String? = null,
    @SerialName("device_type")
    val deviceType: Int,
    val timestamp: Long,
    val hr: Int,
    val hrStatus: Int,
    val ibi: List<Int>,
    val ibiStatus: List<Int>,
    val received: Long,
    val created_at: String? = null
)

