package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing location sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the location entry. Auto-generated when inserting into Supabase.
 * @property deviceType Type of device (e.g., "phone", "watch").
 * @property timestamp Unix timestamp in milliseconds when the location was recorded.
 * @property accuracy Location accuracy in meters.
 * @property altitude Altitude in meters above sea level.
 * @property latitude Latitude coordinate in degrees.
 * @property longitude Longitude coordinate in degrees.
 * @property speed Speed in meters per second.
 * @property received Timestamp when the data was received by the watch (Unix timestamp in milliseconds).
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class LocationSensorData(
    val uuid: String? = null,
    val deviceType: String,
    val timestamp: Long,
    val accuracy: Float,
    val altitude: Double,
    val latitude: Double,
    val longitude: Double,
    val speed: Float,
    val received: Long,
    val created_at: String? = null
)

