package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing PPG (Photoplethysmography) sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the PPG entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the PPG data was recorded.
 * @property green Green light intensity value.
 * @property greenStatus Status of the green light measurement.
 * @property red Red light intensity value.
 * @property redStatus Status of the red light measurement.
 * @property ir Infrared light intensity value.
 * @property irStatus Status of the infrared light measurement.
 * @property received Timestamp when the data was received by the watch (Unix timestamp in milliseconds).
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class PPGSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val green: Int,
    val greenStatus: Int,
    val red: Int,
    val redStatus: Int,
    val ir: Int,
    val irStatus: Int,
    val received: Long,
    val created_at: String? = null
)

