package kaist.iclab.mobiletracker.data.sensors.watch

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing skin temperature sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the skin temperature entry. Auto-generated when inserting into Supabase.
 * @property timestamp Timestamp in "YYYY-MM-DD HH:mm:ss" format when the skin temperature data was recorded.
 * @property ambientTemp Ambient temperature in degrees Celsius.
 * @property objectTemp Object (skin) temperature in degrees Celsius.
 * @property status Status of the temperature measurement.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class SkinTemperatureSensorData(
    val uuid: String? = null,
    val timestamp: String,
    val ambientTemp: Float,
    val objectTemp: Float,
    val status: Int,
    val created_at: String? = null
)

