# GitLab CI configuration for building tracker-library
stages:
  - build

variables:
  ANDROID_COMPILE_SDK: "36"
  ANDROID_BUILD_TOOLS: "35.0.0"
  ANDROID_SDK_TOOLS: "11076708"

build-tracker-library:
  stage: build
  image: jangrewe/gitlab-ci-android
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/
      - tracker-library/build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
  script:
    - ./gradlew :tracker-library:assembleRelease --no-daemon --stacktrace
    - ./gradlew :tracker-library:bundleReleaseAar --no-daemon --stacktrace
  artifacts:
    paths:
      - tracker-library/build/outputs/aar/*.aar
    expire_in: 30 days
  only:
    changes:
      - tracker-library/**/*
      - samsung-health-data-api/**/*
      - samsung-health-sensor-api/**/*
      - build-logic/**/*
      - gradle/**/*
      - build.gradle.kts
      - settings.gradle.kts

