package kaist.iclab.mobiletracker.data.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing ambient light sensor data from the phone device.
 *
 * @property uuid Unique identifier for the ambient light sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the ambient light data was recorded.
 * @property value Ambient light value in lux (illuminance).
 * @property accuracy Sensor accuracy (0 = SENSOR_STATUS_UNRELIABLE, 1 = SENSOR_STATUS_ACCURACY_LOW, 2 = SENSOR_STATUS_ACCURACY_MEDIUM, 3 = SENSOR_STATUS_ACCURACY_HIGH).
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class AmbientLightSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val value: Float,
    val accuracy: Int,
    val created_at: String? = null
)

