package kaist.iclab.mobiletracker.data.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing app usage statistics sensor data from the phone device.
 *
 * @property uuid Unique identifier for the app usage stat sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the app usage data was recorded.
 * @property endTime Unix timestamp in milliseconds when the app usage period ended.
 * @property isSystemApp Whether the app is a system app.
 * @property isUpdatedSystemApp Whether the app is an updated system app.
 * @property lastTimeUsed Unix timestamp in milliseconds when the app was last used.
 * @property name Name of the app.
 * @property packageName Package name of the app.
 * @property startTime Unix timestamp in milliseconds when the app usage period started.
 * @property totalTimeForeground Total time the app was in foreground in milliseconds.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class AppUsageStatSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val endTime: Long,
    val isSystemApp: Boolean,
    val isUpdatedSystemApp: Boolean,
    val lastTimeUsed: Long,
    val name: String,
    val packageName: String,
    val startTime: Long,
    val totalTimeForeground: Long,
    val created_at: String? = null
)

