package kaist.iclab.mobiletracker.data.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing message sensor data from the phone device.
 *
 * @property uuid Unique identifier for the message sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the message data was recorded.
 * @property contact Contact name associated with the message.
 * @property isPinned Whether the message is pinned.
 * @property isStarred Whether the message is starred.
 * @property messageBox Type of message box (e.g., "inbox", "sent", "draft").
 * @property messageClass Classification of the message.
 * @property number Phone number associated with the message.
 * @property timesContacted Number of times this contact has been contacted.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class MessageSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val contact: String,
    val isPinned: Boolean,
    val isStarred: Boolean,
    val messageBox: String,
    val messageClass: String,
    val number: String,
    val timesContacted: Int,
    val created_at: String? = null
)

