package kaist.iclab.mobiletracker.data.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing location sensor data from the phone device.
 *
 * @property uuid Unique identifier for the location sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the location was recorded.
 * @property accuracy Location accuracy in meters.
 * @property altitude Altitude in meters above sea level.
 * @property latitude Latitude coordinate in degrees.
 * @property longitude Longitude coordinate in degrees.
 * @property speed Speed in meters per second.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class PhoneLocationSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val accuracy: Float,
    val altitude: Float,
    val latitude: Float,
    val longitude: Float,
    val speed: Float,
    val created_at: String? = null
)

