package kaist.iclab.mobiletracker.data.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing physical activity transition sensor data from the phone device.
 *
 * @property uuid Unique identifier for the physical activity transition entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the transition was recorded.
 * @property transitionType Type of physical activity transition (e.g., "enter", "exit").
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class PhysicalActivityTransitionSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val transitionType: String,
    val created_at: String? = null
)

