package kaist.iclab.mobiletracker.data.sensors.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing battery sensor data from the phone device.
 *
 * @property uuid Unique identifier for the battery sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the battery data was recorded.
 * @property level Battery level as a percentage (0.0 to 100.0).
 * @property plugged Charging state (e.g., "AC", "USB", "Wireless", "none").
 * @property status Battery status (e.g., "charging", "discharging", "full", "not_charging").
 * @property temperature Battery temperature in degrees Celsius.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class BatterySensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val level: Float,
    val plugged: String,
    val status: String,
    val temperature: Int,
    val created_at: String? = null
)

