package kaist.iclab.mobiletracker.data.sensors.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing campaign data.
 *
 * @property id Unique identifier for the campaign entry (integer primary key).
 * @property name Name of the campaign.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class CampaignData(
    val id: Int? = null,
    val name: String,
    val created_at: String? = null
)

