package kaist.iclab.mobiletracker.data.sensors.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing installed app sensor data from the phone device.
 *
 * @property uuid Unique identifier for the installed app sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the app data was recorded.
 * @property firstInstallTime Unix timestamp in milliseconds when the app was first installed.
 * @property isSystemApp Whether the app is a system app.
 * @property isUpdatedSystemApp Whether the app is an updated system app.
 * @property lastUpdateTime Unix timestamp in milliseconds when the app was last updated.
 * @property name Name of the app.
 * @property packageName Package name of the app.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class InstalledAppSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val firstInstallTime: Long,
    val isSystemApp: Boolean,
    val isUpdatedSystemApp: Boolean,
    val lastUpdateTime: Long,
    val name: String,
    val packageName: String,
    val created_at: String? = null
)

