package kaist.iclab.mobiletracker.data.sensors.phone

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing WiFi sensor data from the phone device.
 *
 * @property uuid Unique identifier for the WiFi sensor entry. Auto-generated when inserting into Supabase.
 * @property timestamp Unix timestamp in milliseconds when the WiFi data was recorded.
 * @property bssid Basic Service Set Identifier (MAC address) of the WiFi access point.
 * @property frequency WiFi frequency in MHz.
 * @property rssi Received Signal Strength Indicator in dBm.
 * @property ssid Service Set Identifier (network name) of the WiFi access point.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class WifiSensorData(
    val uuid: String? = null,
    val timestamp: Long,
    val bssid: String,
    val frequency: Int,
    val rssi: Int,
    val ssid: String,
    val created_at: String? = null
)

