package kaist.iclab.mobiletracker.services

import android.util.Log
import io.github.jan.supabase.postgrest.from
import kaist.iclab.mobiletracker.config.AppConfig
import kaist.iclab.mobiletracker.data.watch.LocationSensorData
import kaist.iclab.mobiletracker.helpers.SupabaseHelper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import java.util.UUID

/**
 * Service for handling location sensor data operations with Supabase
 */
class LocationSensorService(private val supabaseHelper: SupabaseHelper = SupabaseHelper()) {
    private val supabaseClient = supabaseHelper.supabaseClient

    /**
     * Insert location sensor data into Supabase
     * 
     * Maps LocationSensorData to Supabase location_sensor table:
     * - uuid: generated UUID (required)
     * - timestamp: from CSV (required)
     * - latitude: from CSV (required, Double)
     * - longitude: from CSV (required, Double)
     * - altitude: from CSV (required, Double)
     * - speed: from CSV (required, Float)
     * - accuracy: from CSV (required, Float)
     * - created_at: auto-generated by Supabase (excluded from insert)
     */
    fun insertLocationSensorData(locationData: LocationSensorData) {
        CoroutineScope(Dispatchers.IO).launch {
            try {
                val data = locationData.copy(
                    uuid = UUID.randomUUID().toString(),
                    created_at = null // Explicitly exclude, will be auto-generated by Supabase
                )
                supabaseClient.from("location_sensor").insert(data)
                Log.d(AppConfig.LogTags.PHONE_SUPABASE, "Location sensor data inserted successfully: uuid=${data.uuid}, timestamp=${data.timestamp}")
            } catch (e: Exception) {
                Log.e(AppConfig.LogTags.PHONE_SUPABASE, "Error inserting location sensor data: ${e.message}", e)
            }
        }
    }

    /**
     * Insert multiple location sensor data entries into Supabase
     * 
     * Ensures all data matches LocationSensorData structure:
     * - Generates UUID for each entry
     * - Validates field types match data class (timestamp: Long, latitude/longitude/altitude: Double, speed/accuracy: Float)
     * - Excludes created_at (auto-generated by Supabase)
     */
    fun insertLocationSensorDataBatch(locationDataList: List<LocationSensorData>) {
        CoroutineScope(Dispatchers.IO).launch {
            try {
                if (locationDataList.isEmpty()) {
                    Log.w(AppConfig.LogTags.PHONE_SUPABASE, "Empty location data list, skipping insert")
                    return@launch
                }
                
                val dataList = locationDataList.map { locationData ->
                    locationData.copy(
                        uuid = UUID.randomUUID().toString(),
                        created_at = null // Explicitly exclude, will be auto-generated by Supabase
                    )
                }
                supabaseClient.from("location_sensor").insert(dataList)
                Log.d(AppConfig.LogTags.PHONE_SUPABASE, "Inserted ${dataList.size} location sensor data entries")
            } catch (e: Exception) {
                Log.e(AppConfig.LogTags.PHONE_SUPABASE, "Error inserting location sensor data batch: ${e.message}", e)
            }
        }
    }
}

