package kaist.iclab.mobiletracker.data.watch

import kotlinx.serialization.Serializable

/**
 * Supabase data class representing EDA (Electrodermal Activity) sensor data from the wearable device.
 *
 * @property uuid Unique identifier for the EDA entry. Auto-generated when inserting into Supabase.
 * @property timestamp Timestamp in "YYYY-MM-DD HH:mm:ss" format when the EDA data was recorded.
 * @property skinConductance Skin conductance value in microsiemens (μS).
 * @property status Status of the EDA measurement.
 * @property created_at Timestamp when the record was created in Supabase. Auto-generated by the database.
 */
@Serializable
data class EDASensorData(
    val uuid: String? = null,
    val timestamp: String,
    val skinConductance: Float,
    val status: Int,
    val created_at: String? = null
)

