package kaist.iclab.mobiletracker.db.entity.watch

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for storing accelerometer sensor data received from watch.
 * 
 * @property id Auto-generated primary key
 * @property eventId Unique event identifier generated by watch (UUID v4)
 * @property received Timestamp when phone received the data from watch (milliseconds)
 * @property timestamp Timestamp when watch recorded the data (milliseconds)
 * @property x Acceleration along x-axis (m/s²)
 * @property y Acceleration along y-axis (m/s²)
 * @property z Acceleration along z-axis (m/s²)
 */
@Entity(tableName = "watch_accelerometer")
data class WatchAccelerometerEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val eventId: String = "",
    val uuid: String = "",
    val received: Long,
    val timestamp: Long,
    val x: Float,
    val y: Float,
    val z: Float
)
