name: 2. Build AAR and APK Files 

on:
  workflow_dispatch:
    inputs:
      build_library:
        description: 'Build tracker-library AAR'
        type: boolean
        default: false
      build_wearable:
        description: 'Build example-wearable-tracker APK'
        type: boolean
        default: false

# Common setup steps used by both jobs
defaults:
  run:
    shell: bash

jobs:
  build-library:
    name: Build Tracker Library
    runs-on: ubuntu-latest
    if: ${{ inputs.build_library }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew :tracker-library:assembleRelease :tracker-library:bundleReleaseAar --no-daemon

  build-wearable:
    name: Build Wearable Tracker
    runs-on: ubuntu-latest
    if: ${{ inputs.build_wearable }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew :example-wearable-tracker:assembleRelease --no-daemon
