name: 1. Code Sync and Validation

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Build Compatibility
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Validate tracker-library builds
        run: ./gradlew :tracker-library:assembleRelease --no-daemon --continue || echo "::error::tracker-library build failed"
        
      - name: Validate app-wearable-tracker builds
        run: ./gradlew :app-wearable-tracker:assembleRelease --no-daemon --continue || echo "::error::app-wearable-tracker build failed"
        
      - name: Build Status Summary
        if: always()
        run: |
          echo "## Build Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "- tracker-library: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- app-wearable-tracker: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY

